version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t sample-spring .
      - docker tag sample-spring:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sample-spring:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sample-spring:latest